// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insights.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInsight = `-- name: CreateInsight :one
INSERT INTO insights (
  entry_id, themes, feelings, summary, follow_up
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, entry_id, themes, feelings, summary, follow_up, created_at
`

type CreateInsightParams struct {
	EntryID  pgtype.Int4
	Themes   []string
	Feelings []string
	Summary  string
	FollowUp string
}

func (q *Queries) CreateInsight(ctx context.Context, arg CreateInsightParams) (Insight, error) {
	row := q.db.QueryRow(ctx, createInsight,
		arg.EntryID,
		arg.Themes,
		arg.Feelings,
		arg.Summary,
		arg.FollowUp,
	)
	var i Insight
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.Themes,
		&i.Feelings,
		&i.Summary,
		&i.FollowUp,
		&i.CreatedAt,
	)
	return i, err
}

const getInsightByEntryID = `-- name: GetInsightByEntryID :one
SELECT id, entry_id, themes, feelings, summary, follow_up, created_at from insights 
WHERE entry_id = $1 LIMIT 1
`

func (q *Queries) GetInsightByEntryID(ctx context.Context, entryID pgtype.Int4) (Insight, error) {
	row := q.db.QueryRow(ctx, getInsightByEntryID, entryID)
	var i Insight
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.Themes,
		&i.Feelings,
		&i.Summary,
		&i.FollowUp,
		&i.CreatedAt,
	)
	return i, err
}
