// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journal_entries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEntrieByUser = `-- name: CountEntrieByUser :one
SELECT COUNT(*) FROM journal_entries
WHERE user_id = $1
`

func (q *Queries) CountEntrieByUser(ctx context.Context, userID pgtype.Int4) (int64, error) {
	row := q.db.QueryRow(ctx, countEntrieByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJournalEntry = `-- name: CreateJournalEntry :one
INSERT INTO journal_entries (
  user_id, content
) VALUES ($1, $2)
RETURNING id, user_id, content, created_at
`

type CreateJournalEntryParams struct {
	UserID  pgtype.Int4
	Content string
}

func (q *Queries) CreateJournalEntry(ctx context.Context, arg CreateJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, createJournalEntry, arg.UserID, arg.Content)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getSingleEntryByIDs = `-- name: GetSingleEntryByIDs :one
SELECT id, user_id, content, created_at FROM journal_entries
WHERE user_id = $1 AND id = $2 LIMIT 1
`

type GetSingleEntryByIDsParams struct {
	UserID pgtype.Int4
	ID     int32
}

func (q *Queries) GetSingleEntryByIDs(ctx context.Context, arg GetSingleEntryByIDsParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, getSingleEntryByIDs, arg.UserID, arg.ID)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listEntriesByUser = `-- name: ListEntriesByUser :many
SELECT id, user_id, content, created_at FROM journal_entries
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListEntriesByUserParams struct {
	UserID pgtype.Int4
	Limit  int32
	Offset int32
}

func (q *Queries) ListEntriesByUser(ctx context.Context, arg ListEntriesByUserParams) ([]JournalEntry, error) {
	rows, err := q.db.Query(ctx, listEntriesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalEntry
	for rows.Next() {
		var i JournalEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
