// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Insight struct {
	ID        int32
	EntryID   pgtype.Int4
	Themes    []string
	Feelings  []string
	Summary   string
	FollowUp  string
	CreatedAt pgtype.Timestamptz
}

type JournalEntry struct {
	ID        int32
	UserID    pgtype.Int4
	Content   string
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID               int32
	Email            string
	Name             string
	PasswordHash     string
	IsPro            pgtype.Bool
	TrialEntriesUsed pgtype.Int4
	CreatedAt        pgtype.Timestamptz
}
