// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email, name, password_hash
) VALUES ($1, $2, $3)
RETURNING id, email, name, password_hash, is_pro, trial_entries_used, created_at
`

type CreateUserParams struct {
	Email        string
	Name         string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsPro,
		&i.TrialEntriesUsed,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, is_pro, trial_entries_used, created_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsPro,
		&i.TrialEntriesUsed,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, is_pro, trial_entries_used, created_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsPro,
		&i.TrialEntriesUsed,
		&i.CreatedAt,
	)
	return i, err
}

const setUserPro = `-- name: SetUserPro :one
UPDATE users 
set is_pro =$2
WHERE id = $1
RETURNING id, email, name, password_hash, is_pro, trial_entries_used, created_at
`

type SetUserProParams struct {
	ID    int32
	IsPro pgtype.Bool
}

func (q *Queries) SetUserPro(ctx context.Context, arg SetUserProParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserPro, arg.ID, arg.IsPro)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsPro,
		&i.TrialEntriesUsed,
		&i.CreatedAt,
	)
	return i, err
}

const updateTrialEntriesUsed = `-- name: UpdateTrialEntriesUsed :one
UPDATE users 
set trial_entries_used = trial_entries_used + 1
WHERE id = $1
RETURNING trial_entries_used
`

func (q *Queries) UpdateTrialEntriesUsed(ctx context.Context, id int32) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, updateTrialEntriesUsed, id)
	var trial_entries_used pgtype.Int4
	err := row.Scan(&trial_entries_used)
	return trial_entries_used, err
}
